// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/tag.proto

package taskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsSystem      bool                   `protobuf:"varint,2,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_proto_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TagResponse) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

type TagPaginationMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagPaginationMeta) Reset() {
	*x = TagPaginationMeta{}
	mi := &file_proto_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagPaginationMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagPaginationMeta) ProtoMessage() {}

func (x *TagPaginationMeta) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagPaginationMeta.ProtoReflect.Descriptor instead.
func (*TagPaginationMeta) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{1}
}

func (x *TagPaginationMeta) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *TagPaginationMeta) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TagPaginationMeta) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *TagPaginationMeta) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type CreateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_proto_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{3}
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateTagRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_proto_tag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{5}
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_proto_tag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{7}
}

type GetTagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_proto_tag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{8}
}

func (x *GetTagsRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTagsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*TagResponse         `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *TagPaginationMeta     `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_proto_tag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{9}
}

func (x *GetTagsResponse) GetData() []*TagResponse {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTagsResponse) GetPagination() *TagPaginationMeta {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_tag_proto protoreflect.FileDescriptor

const file_proto_tag_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tag.proto\x12\x0etaskTracker.v1\">\n" +
	"\vTagResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tis_system\x18\x02 \x01(\bR\bisSystem\"\x8e\x01\n" +
	"\x11TagPaginationMeta\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"&\n" +
	"\x10CreateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x13\n" +
	"\x11CreateTagResponse\"A\n" +
	"\x10UpdateTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"\x13\n" +
	"\x11UpdateTagResponse\"&\n" +
	"\x10DeleteTagRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x13\n" +
	"\x11DeleteTagResponse\":\n" +
	"\x0eGetTagsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"\x85\x01\n" +
	"\x0fGetTagsResponse\x12/\n" +
	"\x04data\x18\x01 \x03(\v2\x1b.taskTracker.v1.TagResponseR\x04data\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.taskTracker.v1.TagPaginationMetaR\n" +
	"pagination2\xce\x02\n" +
	"\n" +
	"TagService\x12P\n" +
	"\tCreateTag\x12 .taskTracker.v1.CreateTagRequest\x1a!.taskTracker.v1.CreateTagResponse\x12P\n" +
	"\tUpdateTag\x12 .taskTracker.v1.UpdateTagRequest\x1a!.taskTracker.v1.UpdateTagResponse\x12P\n" +
	"\tDeleteTag\x12 .taskTracker.v1.DeleteTagRequest\x1a!.taskTracker.v1.DeleteTagResponse\x12J\n" +
	"\aGetTags\x12\x1e.taskTracker.v1.GetTagsRequest\x1a\x1f.taskTracker.v1.GetTagsResponseB\rZ\v./v1;taskv1b\x06proto3"

var (
	file_proto_tag_proto_rawDescOnce sync.Once
	file_proto_tag_proto_rawDescData []byte
)

func file_proto_tag_proto_rawDescGZIP() []byte {
	file_proto_tag_proto_rawDescOnce.Do(func() {
		file_proto_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)))
	})
	return file_proto_tag_proto_rawDescData
}

var file_proto_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_tag_proto_goTypes = []any{
	(*TagResponse)(nil),       // 0: taskTracker.v1.TagResponse
	(*TagPaginationMeta)(nil), // 1: taskTracker.v1.TagPaginationMeta
	(*CreateTagRequest)(nil),  // 2: taskTracker.v1.CreateTagRequest
	(*CreateTagResponse)(nil), // 3: taskTracker.v1.CreateTagResponse
	(*UpdateTagRequest)(nil),  // 4: taskTracker.v1.UpdateTagRequest
	(*UpdateTagResponse)(nil), // 5: taskTracker.v1.UpdateTagResponse
	(*DeleteTagRequest)(nil),  // 6: taskTracker.v1.DeleteTagRequest
	(*DeleteTagResponse)(nil), // 7: taskTracker.v1.DeleteTagResponse
	(*GetTagsRequest)(nil),    // 8: taskTracker.v1.GetTagsRequest
	(*GetTagsResponse)(nil),   // 9: taskTracker.v1.GetTagsResponse
}
var file_proto_tag_proto_depIdxs = []int32{
	0, // 0: taskTracker.v1.GetTagsResponse.data:type_name -> taskTracker.v1.TagResponse
	1, // 1: taskTracker.v1.GetTagsResponse.pagination:type_name -> taskTracker.v1.TagPaginationMeta
	2, // 2: taskTracker.v1.TagService.CreateTag:input_type -> taskTracker.v1.CreateTagRequest
	4, // 3: taskTracker.v1.TagService.UpdateTag:input_type -> taskTracker.v1.UpdateTagRequest
	6, // 4: taskTracker.v1.TagService.DeleteTag:input_type -> taskTracker.v1.DeleteTagRequest
	8, // 5: taskTracker.v1.TagService.GetTags:input_type -> taskTracker.v1.GetTagsRequest
	3, // 6: taskTracker.v1.TagService.CreateTag:output_type -> taskTracker.v1.CreateTagResponse
	5, // 7: taskTracker.v1.TagService.UpdateTag:output_type -> taskTracker.v1.UpdateTagResponse
	7, // 8: taskTracker.v1.TagService.DeleteTag:output_type -> taskTracker.v1.DeleteTagResponse
	9, // 9: taskTracker.v1.TagService.GetTags:output_type -> taskTracker.v1.GetTagsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tag_proto_init() }
func file_proto_tag_proto_init() {
	if File_proto_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tag_proto_goTypes,
		DependencyIndexes: file_proto_tag_proto_depIdxs,
		MessageInfos:      file_proto_tag_proto_msgTypes,
	}.Build()
	File_proto_tag_proto = out.File
	file_proto_tag_proto_goTypes = nil
	file_proto_tag_proto_depIdxs = nil
}
