// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/task.proto

package taskv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_UNSPECIFIED TaskStatus = 0
	TaskStatus_TASK_STATUS_NEW         TaskStatus = 1
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 2
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 3
	TaskStatus_TASK_STATUS_CANCELED    TaskStatus = 4
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_UNSPECIFIED",
		1: "TASK_STATUS_NEW",
		2: "TASK_STATUS_IN_PROGRESS",
		3: "TASK_STATUS_DONE",
		4: "TASK_STATUS_CANCELED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_UNSPECIFIED": 0,
		"TASK_STATUS_NEW":         1,
		"TASK_STATUS_IN_PROGRESS": 2,
		"TASK_STATUS_DONE":        3,
		"TASK_STATUS_CANCELED":    4,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

type RecurrenceType int32

const (
	RecurrenceType_RECURRENCE_TYPE_UNSPECIFIED RecurrenceType = 0
	RecurrenceType_RECURRENCE_TYPE_DAILY       RecurrenceType = 1
	RecurrenceType_RECURRENCE_TYPE_MONTHLY     RecurrenceType = 2
	RecurrenceType_RECURRENCE_TYPE_DATES       RecurrenceType = 3
	RecurrenceType_RECURRENCE_TYPE_EVEN        RecurrenceType = 4
	RecurrenceType_RECURRENCE_TYPE_ODD         RecurrenceType = 5
)

// Enum value maps for RecurrenceType.
var (
	RecurrenceType_name = map[int32]string{
		0: "RECURRENCE_TYPE_UNSPECIFIED",
		1: "RECURRENCE_TYPE_DAILY",
		2: "RECURRENCE_TYPE_MONTHLY",
		3: "RECURRENCE_TYPE_DATES",
		4: "RECURRENCE_TYPE_EVEN",
		5: "RECURRENCE_TYPE_ODD",
	}
	RecurrenceType_value = map[string]int32{
		"RECURRENCE_TYPE_UNSPECIFIED": 0,
		"RECURRENCE_TYPE_DAILY":       1,
		"RECURRENCE_TYPE_MONTHLY":     2,
		"RECURRENCE_TYPE_DATES":       3,
		"RECURRENCE_TYPE_EVEN":        4,
		"RECURRENCE_TYPE_ODD":         5,
	}
)

func (x RecurrenceType) Enum() *RecurrenceType {
	p := new(RecurrenceType)
	*p = x
	return p
}

func (x RecurrenceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RecurrenceType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_task_proto_enumTypes[1].Descriptor()
}

func (RecurrenceType) Type() protoreflect.EnumType {
	return &file_proto_task_proto_enumTypes[1]
}

func (x RecurrenceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RecurrenceType.Descriptor instead.
func (RecurrenceType) EnumDescriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

type TaskRecurrence struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Type          RecurrenceType           `protobuf:"varint,1,opt,name=type,proto3,enum=taskTracker.v1.RecurrenceType" json:"type,omitempty"`
	Interval      int32                    `protobuf:"varint,2,opt,name=interval,proto3" json:"interval,omitempty"`
	DayOfMonth    int32                    `protobuf:"varint,3,opt,name=day_of_month,json=dayOfMonth,proto3" json:"day_of_month,omitempty"`
	Specifics     []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=specifics,proto3" json:"specifics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRecurrence) Reset() {
	*x = TaskRecurrence{}
	mi := &file_proto_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRecurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRecurrence) ProtoMessage() {}

func (x *TaskRecurrence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRecurrence.ProtoReflect.Descriptor instead.
func (*TaskRecurrence) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRecurrence) GetType() RecurrenceType {
	if x != nil {
		return x.Type
	}
	return RecurrenceType_RECURRENCE_TYPE_UNSPECIFIED
}

func (x *TaskRecurrence) GetInterval() int32 {
	if x != nil {
		return x.Interval
	}
	return 0
}

func (x *TaskRecurrence) GetDayOfMonth() int32 {
	if x != nil {
		return x.DayOfMonth
	}
	return 0
}

func (x *TaskRecurrence) GetSpecifics() []*timestamppb.Timestamp {
	if x != nil {
		return x.Specifics
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=taskTracker.v1.TaskStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IsRecurring   bool                   `protobuf:"varint,7,opt,name=is_recurring,json=isRecurring,proto3" json:"is_recurring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *Task) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Task) GetIsRecurring() bool {
	if x != nil {
		return x.IsRecurring
	}
	return false
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Recurrence    *TaskRecurrence        `protobuf:"bytes,5,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *CreateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateTaskRequest) GetRecurrence() *TaskRecurrence {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type UpdateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DueDate       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=taskTracker.v1.TaskStatus" json:"status,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Recurrence    *TaskRecurrence        `protobuf:"bytes,7,opt,name=recurrence,proto3" json:"recurrence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetDueDate() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDate
	}
	return nil
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *UpdateTaskRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateTaskRequest) GetRecurrence() *TaskRecurrence {
	if x != nil {
		return x.Recurrence
	}
	return nil
}

type UpdateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskResponse) Reset() {
	*x = UpdateTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskResponse) ProtoMessage() {}

func (x *UpdateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskResponse.ProtoReflect.Descriptor instead.
func (*UpdateTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{5}
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_task_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_proto_task_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{7}
}

type GetTaskByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIDRequest) Reset() {
	*x = GetTaskByIDRequest{}
	mi := &file_proto_task_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIDRequest) ProtoMessage() {}

func (x *GetTaskByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTaskByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{8}
}

func (x *GetTaskByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTaskByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task,proto3" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskByIDResponse) Reset() {
	*x = GetTaskByIDResponse{}
	mi := &file_proto_task_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskByIDResponse) ProtoMessage() {}

func (x *GetTaskByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTaskByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskByIDResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

type PaginationMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CurrentPage   int64                  `protobuf:"varint,1,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalItems    int64                  `protobuf:"varint,3,opt,name=total_items,json=totalItems,proto3" json:"total_items,omitempty"`
	TotalPages    int64                  `protobuf:"varint,4,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaginationMetadata) Reset() {
	*x = PaginationMetadata{}
	mi := &file_proto_task_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaginationMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaginationMetadata) ProtoMessage() {}

func (x *PaginationMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaginationMetadata.ProtoReflect.Descriptor instead.
func (*PaginationMetadata) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{10}
}

func (x *PaginationMetadata) GetCurrentPage() int64 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

func (x *PaginationMetadata) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *PaginationMetadata) GetTotalItems() int64 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PaginationMetadata) GetTotalPages() int64 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

type GetTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        TaskStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=taskTracker.v1.TaskStatus" json:"status,omitempty"`
	DueDateFrom   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=due_date_from,json=dueDateFrom,proto3" json:"due_date_from,omitempty"`
	DueDateTo     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=due_date_to,json=dueDateTo,proto3" json:"due_date_to,omitempty"`
	Page          int64                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksRequest) Reset() {
	*x = GetTasksRequest{}
	mi := &file_proto_task_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksRequest) ProtoMessage() {}

func (x *GetTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksRequest.ProtoReflect.Descriptor instead.
func (*GetTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{11}
}

func (x *GetTasksRequest) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_UNSPECIFIED
}

func (x *GetTasksRequest) GetDueDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDateFrom
	}
	return nil
}

func (x *GetTasksRequest) GetDueDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DueDateTo
	}
	return nil
}

func (x *GetTasksRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetTasksRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Task                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Pagination    *PaginationMetadata    `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTasksResponse) Reset() {
	*x = GetTasksResponse{}
	mi := &file_proto_task_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTasksResponse) ProtoMessage() {}

func (x *GetTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_task_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTasksResponse.ProtoReflect.Descriptor instead.
func (*GetTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_task_proto_rawDescGZIP(), []int{12}
}

func (x *GetTasksResponse) GetData() []*Task {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetTasksResponse) GetPagination() *PaginationMetadata {
	if x != nil {
		return x.Pagination
	}
	return nil
}

var File_proto_task_proto protoreflect.FileDescriptor

const file_proto_task_proto_rawDesc = "" +
	"\n" +
	"\x10proto/task.proto\x12\x0etaskTracker.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbc\x01\n" +
	"\x0eTaskRecurrence\x122\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1e.taskTracker.v1.RecurrenceTypeR\x04type\x12\x1a\n" +
	"\binterval\x18\x02 \x01(\x05R\binterval\x12 \n" +
	"\fday_of_month\x18\x03 \x01(\x05R\n" +
	"dayOfMonth\x128\n" +
	"\tspecifics\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampR\tspecifics\"\xf0\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bdue_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.taskTracker.v1.TaskStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12!\n" +
	"\fis_recurring\x18\a \x01(\bR\visRecurring\"\xd6\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x125\n" +
	"\bdue_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12>\n" +
	"\n" +
	"recurrence\x18\x05 \x01(\v2\x1e.taskTracker.v1.TaskRecurrenceR\n" +
	"recurrence\">\n" +
	"\x12CreateTaskResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.taskTracker.v1.TaskR\x04task\"\x9a\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x125\n" +
	"\bdue_date\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\adueDate\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.taskTracker.v1.TaskStatusR\x06status\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12>\n" +
	"\n" +
	"recurrence\x18\a \x01(\v2\x1e.taskTracker.v1.TaskRecurrenceR\n" +
	"recurrence\"\x14\n" +
	"\x12UpdateTaskResponse\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteTaskResponse\"$\n" +
	"\x12GetTaskByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"?\n" +
	"\x13GetTaskByIDResponse\x12(\n" +
	"\x04task\x18\x01 \x01(\v2\x14.taskTracker.v1.TaskR\x04task\"\x8f\x01\n" +
	"\x12PaginationMetadata\x12!\n" +
	"\fcurrent_page\x18\x01 \x01(\x03R\vcurrentPage\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\x12\x1f\n" +
	"\vtotal_items\x18\x03 \x01(\x03R\n" +
	"totalItems\x12\x1f\n" +
	"\vtotal_pages\x18\x04 \x01(\x03R\n" +
	"totalPages\"\xeb\x01\n" +
	"\x0fGetTasksRequest\x122\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1a.taskTracker.v1.TaskStatusR\x06status\x12>\n" +
	"\rdue_date_from\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vdueDateFrom\x12:\n" +
	"\vdue_date_to\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdueDateTo\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\"\x80\x01\n" +
	"\x10GetTasksResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.taskTracker.v1.TaskR\x04data\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".taskTracker.v1.PaginationMetadataR\n" +
	"pagination*\x8b\x01\n" +
	"\n" +
	"TaskStatus\x12\x1b\n" +
	"\x17TASK_STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fTASK_STATUS_NEW\x10\x01\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x02\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x03\x12\x18\n" +
	"\x14TASK_STATUS_CANCELED\x10\x04*\xb7\x01\n" +
	"\x0eRecurrenceType\x12\x1f\n" +
	"\x1bRECURRENCE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15RECURRENCE_TYPE_DAILY\x10\x01\x12\x1b\n" +
	"\x17RECURRENCE_TYPE_MONTHLY\x10\x02\x12\x19\n" +
	"\x15RECURRENCE_TYPE_DATES\x10\x03\x12\x18\n" +
	"\x14RECURRENCE_TYPE_EVEN\x10\x04\x12\x17\n" +
	"\x13RECURRENCE_TYPE_ODD\x10\x052\xb3\x03\n" +
	"\vTaskService\x12S\n" +
	"\n" +
	"CreateTask\x12!.taskTracker.v1.CreateTaskRequest\x1a\".taskTracker.v1.CreateTaskResponse\x12S\n" +
	"\n" +
	"UpdateTask\x12!.taskTracker.v1.UpdateTaskRequest\x1a\".taskTracker.v1.UpdateTaskResponse\x12S\n" +
	"\n" +
	"DeleteTask\x12!.taskTracker.v1.DeleteTaskRequest\x1a\".taskTracker.v1.DeleteTaskResponse\x12V\n" +
	"\vGetTaskByID\x12\".taskTracker.v1.GetTaskByIDRequest\x1a#.taskTracker.v1.GetTaskByIDResponse\x12M\n" +
	"\bGetTasks\x12\x1f.taskTracker.v1.GetTasksRequest\x1a .taskTracker.v1.GetTasksResponseB\rZ\v./v1;taskv1b\x06proto3"

var (
	file_proto_task_proto_rawDescOnce sync.Once
	file_proto_task_proto_rawDescData []byte
)

func file_proto_task_proto_rawDescGZIP() []byte {
	file_proto_task_proto_rawDescOnce.Do(func() {
		file_proto_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)))
	})
	return file_proto_task_proto_rawDescData
}

var file_proto_task_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_task_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_task_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: taskTracker.v1.TaskStatus
	(RecurrenceType)(0),           // 1: taskTracker.v1.RecurrenceType
	(*TaskRecurrence)(nil),        // 2: taskTracker.v1.TaskRecurrence
	(*Task)(nil),                  // 3: taskTracker.v1.Task
	(*CreateTaskRequest)(nil),     // 4: taskTracker.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),    // 5: taskTracker.v1.CreateTaskResponse
	(*UpdateTaskRequest)(nil),     // 6: taskTracker.v1.UpdateTaskRequest
	(*UpdateTaskResponse)(nil),    // 7: taskTracker.v1.UpdateTaskResponse
	(*DeleteTaskRequest)(nil),     // 8: taskTracker.v1.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),    // 9: taskTracker.v1.DeleteTaskResponse
	(*GetTaskByIDRequest)(nil),    // 10: taskTracker.v1.GetTaskByIDRequest
	(*GetTaskByIDResponse)(nil),   // 11: taskTracker.v1.GetTaskByIDResponse
	(*PaginationMetadata)(nil),    // 12: taskTracker.v1.PaginationMetadata
	(*GetTasksRequest)(nil),       // 13: taskTracker.v1.GetTasksRequest
	(*GetTasksResponse)(nil),      // 14: taskTracker.v1.GetTasksResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_task_proto_depIdxs = []int32{
	1,  // 0: taskTracker.v1.TaskRecurrence.type:type_name -> taskTracker.v1.RecurrenceType
	15, // 1: taskTracker.v1.TaskRecurrence.specifics:type_name -> google.protobuf.Timestamp
	15, // 2: taskTracker.v1.Task.due_date:type_name -> google.protobuf.Timestamp
	0,  // 3: taskTracker.v1.Task.status:type_name -> taskTracker.v1.TaskStatus
	15, // 4: taskTracker.v1.CreateTaskRequest.due_date:type_name -> google.protobuf.Timestamp
	2,  // 5: taskTracker.v1.CreateTaskRequest.recurrence:type_name -> taskTracker.v1.TaskRecurrence
	3,  // 6: taskTracker.v1.CreateTaskResponse.task:type_name -> taskTracker.v1.Task
	15, // 7: taskTracker.v1.UpdateTaskRequest.due_date:type_name -> google.protobuf.Timestamp
	0,  // 8: taskTracker.v1.UpdateTaskRequest.status:type_name -> taskTracker.v1.TaskStatus
	2,  // 9: taskTracker.v1.UpdateTaskRequest.recurrence:type_name -> taskTracker.v1.TaskRecurrence
	3,  // 10: taskTracker.v1.GetTaskByIDResponse.task:type_name -> taskTracker.v1.Task
	0,  // 11: taskTracker.v1.GetTasksRequest.status:type_name -> taskTracker.v1.TaskStatus
	15, // 12: taskTracker.v1.GetTasksRequest.due_date_from:type_name -> google.protobuf.Timestamp
	15, // 13: taskTracker.v1.GetTasksRequest.due_date_to:type_name -> google.protobuf.Timestamp
	3,  // 14: taskTracker.v1.GetTasksResponse.data:type_name -> taskTracker.v1.Task
	12, // 15: taskTracker.v1.GetTasksResponse.pagination:type_name -> taskTracker.v1.PaginationMetadata
	4,  // 16: taskTracker.v1.TaskService.CreateTask:input_type -> taskTracker.v1.CreateTaskRequest
	6,  // 17: taskTracker.v1.TaskService.UpdateTask:input_type -> taskTracker.v1.UpdateTaskRequest
	8,  // 18: taskTracker.v1.TaskService.DeleteTask:input_type -> taskTracker.v1.DeleteTaskRequest
	10, // 19: taskTracker.v1.TaskService.GetTaskByID:input_type -> taskTracker.v1.GetTaskByIDRequest
	13, // 20: taskTracker.v1.TaskService.GetTasks:input_type -> taskTracker.v1.GetTasksRequest
	5,  // 21: taskTracker.v1.TaskService.CreateTask:output_type -> taskTracker.v1.CreateTaskResponse
	7,  // 22: taskTracker.v1.TaskService.UpdateTask:output_type -> taskTracker.v1.UpdateTaskResponse
	9,  // 23: taskTracker.v1.TaskService.DeleteTask:output_type -> taskTracker.v1.DeleteTaskResponse
	11, // 24: taskTracker.v1.TaskService.GetTaskByID:output_type -> taskTracker.v1.GetTaskByIDResponse
	14, // 25: taskTracker.v1.TaskService.GetTasks:output_type -> taskTracker.v1.GetTasksResponse
	21, // [21:26] is the sub-list for method output_type
	16, // [16:21] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_task_proto_init() }
func file_proto_task_proto_init() {
	if File_proto_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_task_proto_rawDesc), len(file_proto_task_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_task_proto_goTypes,
		DependencyIndexes: file_proto_task_proto_depIdxs,
		EnumInfos:         file_proto_task_proto_enumTypes,
		MessageInfos:      file_proto_task_proto_msgTypes,
	}.Build()
	File_proto_task_proto = out.File
	file_proto_task_proto_goTypes = nil
	file_proto_task_proto_depIdxs = nil
}
